# Generated by Django 5.0.4 on 2026-03-25 21:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventrsvp',
            name='unique_event_rsvp',
        ),
        migrations.RemoveConstraint(
            model_name='eventsaved',
            name='unique_user_saved_event',
        ),
        migrations.RenameIndex(
            model_name='eventreminder',
            new_name='event_remin_remind__b3f5c7_idx',
            old_name='reminder_due_idx',
        ),
        migrations.AlterUniqueTogether(
            name='eventrsvp',
            unique_together={('event', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='eventsaved',
            unique_together={('user', 'event')},
        ),
    ]
