# Generated by Django 5.0.4 on 2026-04-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_eventrsvp_unique_event_rsvp_and_more'),
        ('events', '0003_remove_campus_id'),
    ]

    operations = [
    ]
