# Generated by Django 5.0.4 on 2026-03-25 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_1f75db_idx',
            old_name='notif_user_read_idx',
        ),
    ]
