# Generated by Django 5.0.4 on 2026-03-25 21:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='housingsaved',
            name='unique_user_saved_housing',
        ),
        migrations.AlterUniqueTogether(
            name='housingsaved',
            unique_together={('user', 'listing')},
        ),
    ]
