# Generated by Django 5.0.4 on 2026-04-04 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_remove_housingsaved_unique_user_saved_housing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingModuleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'housing_module_settings',
            },
        ),
        migrations.RemoveField(
            model_name='housinglisting',
            name='campus_id',
        ),
        migrations.RemoveField(
            model_name='roommateprofile',
            name='campus_id',
        ),
        migrations.AddField(
            model_name='housingalert',
            name='notify_roommate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housinglisting',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='RoommatePreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_area', models.CharField(blank=True, max_length=200, null=True)),
                ('gender_preference', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], default='any', max_length=10)),
                ('sleep_schedule', models.CharField(blank=True, max_length=20, null=True)),
                ('cleanliness', models.CharField(blank=True, max_length=20, null=True)),
                ('noise_level', models.CharField(blank=True, max_length=20, null=True)),
                ('smoking', models.BooleanField(default=False)),
                ('pets', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'roommate_preferences',
            },
        ),
    ]
