# Generated by Django 5.0.4 on 2026-04-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_alertnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommateprofile',
            name='preferred_areas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
