# Generated by Django 5.0.4 on 2026-04-09 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_roommateprofile_preferred_areas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housingalert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='housingalert',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='housingalert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='housingalert',
            name='label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='housingalert',
            name='max_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='housingalert',
            name='property_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='housingalert',
            name='rule_type',
            field=models.CharField(choices=[('area', 'Area Alert'), ('price_drop', 'Price Alert'), ('listing_available', 'Availability Alert'), ('new_listing', 'New Listing Alert')], default='new_listing', max_length=30),
        ),
        migrations.AddField(
            model_name='housingalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roommatepreference',
            name='preferred_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='UserHousingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_module_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='housing_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_housing_preferences',
            },
        ),
    ]
