# Generated by Django 5.0.4

from django.db import migrations, models


ALERT_RULE_TYPES = [
    ("area",              "Area Alert"),
    ("price_drop",        "Price Alert"),
    ("listing_available", "Availability Alert"),
    ("new_listing",       "New Listing Alert"),
]


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_roommateprofile_preferred_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingalert',
            name='rule_type',
            field=models.CharField(
                max_length=30,
                choices=ALERT_RULE_TYPES,
                default='new_listing',
            ),
        ),
    ]
