# Generated by Django 5.0.4 on 2026-03-25 21:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marketdonationclaim',
            name='unique_claimant_listing',
        ),
        migrations.RemoveConstraint(
            model_name='marketreview',
            name='unique_buyer_listing_review',
        ),
        migrations.RemoveConstraint(
            model_name='marketsavedlisting',
            name='unique_user_saved_listing',
        ),
        migrations.AlterUniqueTogether(
            name='marketdonationclaim',
            unique_together={('claimant', 'listing')},
        ),
        migrations.AlterUniqueTogether(
            name='marketreview',
            unique_together={('buyer', 'listing')},
        ),
        migrations.AlterUniqueTogether(
            name='marketsavedlisting',
            unique_together={('user', 'listing')},
        ),
    ]
