# Generated by Django 5.0.4 on 2026-04-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_remove_marketdonationclaim_unique_claimant_listing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketlisting',
            old_name='image_urls',
            new_name='image_data',
        ),
        migrations.RemoveField(
            model_name='marketlisting',
            name='campus_id',
        ),
    ]
