# Generated by Django 5.0.4 on 2026-04-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_remove_studygroupmember_unique_group_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='campus_id',
            field=models.CharField(blank=True, default='global', max_length=80),
        ),
        migrations.AlterField(
            model_name='studyquestion',
            name='campus_id',
            field=models.CharField(blank=True, default='global', max_length=80),
        ),
        migrations.AlterField(
            model_name='studyresource',
            name='campus_id',
            field=models.CharField(blank=True, default='global', max_length=80),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='campus_id',
            field=models.CharField(blank=True, default='global', max_length=80),
        ),
    ]
