# Generated by Django 5.0.4 on 2026-04-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_alter_studygroup_campus_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='campus_id',
        ),
        migrations.RemoveField(
            model_name='studyquestion',
            name='campus_id',
        ),
        migrations.RemoveField(
            model_name='studyresource',
            name='campus_id',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='campus_id',
        ),
    ]
