# Generated by Django 5.0.4 on 2026-04-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_remove_studyresource_uploader_studyresource_topic_and_more'),
        ('study', '0006_remove_campus_id'),
    ]

    operations = [
    ]
