# Generated by Django 5.0.4 on 2026-04-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_merge_20260401_2336'),
        ('study', '0008_sessions'),
    ]

    operations = [
    ]
