# Generated by Django 5.0.4 on 2026-04-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_merge_0007_merge_20260401_2336_0008_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroupsession',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location or online link', max_length=200, null=True),
        ),
    ]
