# Generated by Django 5.0.4 on 2026-04-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0010_alter_studygroupsession_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studygroupmember',
            old_name='is_admin',
            new_name='is_creator',
        ),
    ]
